In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [4]:
path_to_file = 'C://Users//DELL//Downloads//E.M.Forster.txt'

In [6]:
text = open(path_to_file, 'r', encoding='utf-8').read()

In [7]:
print(text[:500])


Chapter I
The Bertolini


“The Signora had no business to do it,” said Miss Bartlett, “no
business at all. She promised us south rooms with a view close
together, instead of which here are north rooms, looking into a
courtyard, and a long way apart. Oh, Lucy!”

“And a Cockney, besides!” said Lucy, who had been further saddened by
the Signora’s unexpected accent. “It might be London.” She looked at
the two rows of English people who were sitting at the table; at the
row of white bottles of water 


# Finding the Unique Characters

In [8]:
# Finding The unique characters in the file
unique = sorted(set(text))
print(unique)
len(unique)

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '=', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '£', 'à', 'â', 'ä', 'æ', 'ç', 'è', 'é', 'ê', 'ì', 'í', 'ó', 'ö', 'ù', 'Œ', 'œ', '—', '‘', '’', '“', '”']


103

# Text Processing

Text Vectorization: Since a neural network cannot process raw string data, we need to assign a numerical value to each character. To achieve this, we can create two dictionaries: one to convert characters into numeric indices and another to translate numeric indices back into characters.

In [9]:
char_to_ind = {u:i for i, u in enumerate(unique)}

In [10]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 '*': 8,
 ',': 9,
 '-': 10,
 '.': 11,
 '0': 12,
 '1': 13,
 '2': 14,
 '3': 15,
 '4': 16,
 '5': 17,
 '6': 18,
 '7': 19,
 '8': 20,
 '9': 21,
 ':': 22,
 ';': 23,
 '=': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '£': 82,
 'à': 83,
 'â': 84,
 'ä': 85,
 'æ': 86,
 'ç': 87,
 'è': 88,
 'é': 89,
 'ê': 90,
 'ì': 91,
 'í': 92,
 'ó': 93,
 'ö': 94,
 'ù': 95,
 'Œ': 96,
 'œ': 97,
 '—': 98,
 '‘': 99,
 '’': 100

In [11]:
ind_to_char = np.array(unique) # Index to character

In [12]:
ind_to_char

array(['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '=', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
       'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', '£', 'à', 'â', 'ä', 'æ', 'ç', 'è', 'é', 'ê',
       'ì', 'í', 'ó', 'ö', 'ù', 'Œ', 'œ', '—', '‘', '’', '“', '”'],
      dtype='<U1')

In [13]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [14]:
encoded_text

array([28, 63, 56, ...,  1,  1,  0])

We now have a mapping that we can use to switch between characters and numbers.

In [15]:
sample_data = text[:20]
sample_data

'Chapter I\nThe Bertol'

In [16]:
encoded_text[:20]

array([28, 63, 56, 71, 75, 60, 73,  1, 34,  0, 45, 63, 60,  1, 27, 60, 73,
       75, 70, 67])

In [17]:
encoded_text[:20]

array([28, 63, 56, 71, 75, 60, 73,  1, 34,  0, 45, 63, 60,  1, 27, 60, 73,
       75, 70, 67])

# Creating Batches

In general, our goal is to have the model predict the following character with the best probability given a historical series of characters. The length of the historical series is up to the user. A sequence that is too short leaves us with insufficient information (e.g., given the letter "a," what is the next character), whereas a sequence that is too long causes training to take too long and is likely to overfit to sequence characters that are irrelevant to characters further out. Although there is no ideal sequence length, you should take into account the text itself, the length of typical phrases, and a good understanding of the letters and words that are related to one another.

In [18]:
print(text[:500])

Chapter I
The Bertolini


“The Signora had no business to do it,” said Miss Bartlett, “no
business at all. She promised us south rooms with a view close
together, instead of which here are north rooms, looking into a
courtyard, and a long way apart. Oh, Lucy!”

“And a Cockney, besides!” said Lucy, who had been further saddened by
the Signora’s unexpected accent. “It might be London.” She looked at
the two rows of English people who were sitting at the table; at the
row of white bottles of water 


In [19]:
stanza_line= 'The Signora had no business to do it,” said Miss Bartlett, “no business at all. She promised us south rooms with a view close together, instead of which here are north rooms, looking into a courtyard, and a long way apart. Oh, Lucy'

In [20]:
len(stanza_line)

231

So, on an average we can take length of line as 200

Training

In [21]:
seq_len = 200

In [22]:
total_num_seq = len(text)//(seq_len+1)

In [23]:
total_num_seq

11857

These individual character requests are transformed into sequences we can input as a batch using the batch method. Because zero indexing is used, we use seq_len+1. What drop_remainder signifies is as follows:

(Optional) Drop remaining items. a tf.bool scalar tf.Tensor that indicates whether the previous batch should be eliminated if it contains less elements than batch_size; the default approach is to keep the larger batch.

In [24]:
# Creating  Training Sequences
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

for i in char_dataset.take(500):
     print(ind_to_char[i.numpy()])

C
h
a
p
t
e
r
 
I


T
h
e
 
B
e
r
t
o
l
i
n
i






“
T
h
e
 
S
i
g
n
o
r
a
 
h
a
d
 
n
o
 
b
u
s
i
n
e
s
s
 
t
o
 
d
o
 
i
t
,
”
 
s
a
i
d
 
M
i
s
s
 
B
a
r
t
l
e
t
t
,
 
“
n
o


b
u
s
i
n
e
s
s
 
a
t
 
a
l
l
.
 
S
h
e
 
p
r
o
m
i
s
e
d
 
u
s
 
s
o
u
t
h
 
r
o
o
m
s
 
w
i
t
h
 
a
 
v
i
e
w
 
c
l
o
s
e


t
o
g
e
t
h
e
r
,
 
i
n
s
t
e
a
d
 
o
f
 
w
h
i
c
h
 
h
e
r
e
 
a
r
e
 
n
o
r
t
h
 
r
o
o
m
s
,
 
l
o
o
k
i
n
g
 
i
n
t
o
 
a


c
o
u
r
t
y
a
r
d
,
 
a
n
d
 
a
 
l
o
n
g
 
w
a
y
 
a
p
a
r
t
.
 
O
h
,
 
L
u
c
y
!
”




“
A
n
d
 
a
 
C
o
c
k
n
e
y
,
 
b
e
s
i
d
e
s
!
”
 
s
a
i
d
 
L
u
c
y
,
 
w
h
o
 
h
a
d
 
b
e
e
n
 
f
u
r
t
h
e
r
 
s
a
d
d
e
n
e
d
 
b
y


t
h
e
 
S
i
g
n
o
r
a
’
s
 
u
n
e
x
p
e
c
t
e
d
 
a
c
c
e
n
t
.
 
“
I
t
 
m
i
g
h
t
 
b
e
 
L
o
n
d
o
n
.
”
 
S
h
e
 
l
o
o
k
e
d
 
a
t


t
h
e
 
t
w
o
 
r
o
w
s
 
o
f
 
E
n
g
l
i
s
h
 
p
e
o
p
l
e
 
w
h
o
 
w
e
r
e
 
s
i
t
t
i
n
g
 
a
t
 
t
h
e
 
t
a
b
l
e
;
 
a
t
 
t
h
e


r
o
w
 
o
f
 
w
h
i
t
e
 
b
o
t
t
l
e
s
 
o
f
 
w
a
t
e
r
 


In [25]:
sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

We now have our sequences, and to produce our target text sequences, we will carry out the following procedures for each of them:

Take the input text flow.
Shift the input text sequence one step ahead before assigning the target text sequence.
Combine them into a tuple.

In [26]:
def create_seq_targets(seq):
    input_txt = seq[:-1]
    target_txt = seq[1:]
    return input_txt, target_txt

In [27]:
data = sequences.map(create_seq_targets)     

In [28]:
for input_txt, target_txt in  data.take(1):
    print(input_txt.numpy())
    print(''.join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    # There is an extra whitespace!
    print(''.join(ind_to_char[target_txt.numpy()]))

[ 28  63  56  71  75  60  73   1  34   0  45  63  60   1  27  60  73  75
  70  67  64  69  64   0   0   0 101  45  63  60   1  44  64  62  69  70
  73  56   1  63  56  59   1  69  70   1  57  76  74  64  69  60  74  74
   1  75  70   1  59  70   1  64  75   9 102   1  74  56  64  59   1  38
  64  74  74   1  27  56  73  75  67  60  75  75   9   1 101  69  70   0
  57  76  74  64  69  60  74  74   1  56  75   1  56  67  67  11   1  44
  63  60   1  71  73  70  68  64  74  60  59   1  76  74   1  74  70  76
  75  63   1  73  70  70  68  74   1  78  64  75  63   1  56   1  77  64
  60  78   1  58  67  70  74  60   0  75  70  62  60  75  63  60  73   9
   1  64  69  74  75  60  56  59   1  70  61   1  78  63  64  58  63   1
  63  60  73  60   1  56  73  60   1  69  70  73  75  63   1  73  70  70
  68  74]
Chapter I
The Bertolini


“The Signora had no business to do it,” said Miss Bartlett, “no
business at all. She promised us south rooms with a view close
together, instead of which here ar

Generating Training Batches

To prevent the model from overfitting to specific parts of the text, we'll shuffle these sequences into a random order. This approach ensures that the model can generate characters from any seed text. With the sequences ready, we can now create the training batches.

In [45]:
# declaring Batch size
batch_size = 128

# Buffer size to shuffle the dataset so it doesn't attempt to shuffle
# the entire sequence in memory. Instead, it maintains a buffer in which it shuffles elements
buffer_size = 10000

dataset = data.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [46]:
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 200), dtype=tf.int32, name=None), TensorSpec(shape=(128, 200), dtype=tf.int32, name=None))>

Creating the Model

With two LSTM layers and an initial embedding layer, our LSTM-based model will also have a few more properties. The DeepMoji, whose original source code can be accessed here, served as the inspiration for this model's architecture.

The input layer will be the embedding layer, which functions as a sort of lookup table that converts each character's numerical indices into a vector with a "embedding dim" number of dimensions. As you can expect, the training becomes more difficult as the embedding size increases. This concept is comparable to word2vec, which maps words to an n-dimensional space. Results that have been embedded before being fed directly into the LSTM are typically more realistic.

In [47]:

# finding the Length of the vocabulary in chars
vocab_size = len(unique)

# The embedding dimension
embed_dim = 64

# Number of RNN units
rnn_neurons = 1026

In [56]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU, Input

Setting up Loss Function

We may import sparse categorical crossentropy from Keras to calculate our loss. Additionally, we'll set this to logits=True.

In [57]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [58]:
def sparse_cat_loss(y_true, y_pred):
    return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()
    
    # Defining input shape using Input layer
    model.add(Input(shape=(None,), batch_size=batch_size))
    
    # Embedding layer without batch_input_shape
    model.add(Embedding(vocab_size, embed_dim))
    
    # GRU layer
    model.add(GRU(rnn_neurons, return_sequences=True, stateful=True, recurrent_initializer='glorot_uniform'))
    
    # Final Dense layer to predict
    model.add(Dense(vocab_size))
    
    # Compilling the model
    model.compile(optimizer='adam', loss=sparse_cat_loss)
    
    return model

# Assuming vocab_size, embed_dim, rnn_neurons, and batch_size are defined
model = create_model(
    vocab_size=vocab_size,
    embed_dim=embed_dim,
    rnn_neurons=rnn_neurons,
    batch_size=batch_size
)
     

In [59]:

model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (128, None, 64)        │         6,592 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_2 (GRU)                     │ (128, None, 1026)      │     3,361,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (128, None, 103)       │       105,781 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,473,549 (13.25 MB)

 Trainable params: 3,473,549 (13.25 MB)

 Non-trainable params: 0 (0.00 B)

Training the model

Before we invest too much time in training, let's make sure our model is happy with everything. To verify that the model now predicts random characters devoid of any training, let's pass in a batch.

In [60]:
for input_example_batch, target_example_batch in dataset.take(1):

  # Predict off some random batch
  example_batch_predictions = model(input_example_batch)

  # Displaying the dimensions of the predictions
  print(example_batch_predictions.shape, " <=== (batch_size, sequence_length, vocab_size)")

(128, 200, 103)  <=== (batch_size, sequence_length, vocab_size)


In [61]:
example_batch_predictions

<tf.Tensor: shape=(128, 200, 103), dtype=float32, numpy=
array([[[ 1.85161573e-03,  2.64890771e-03, -1.08957419e-03, ...,
         -2.39001820e-03, -1.93941919e-03, -9.76242009e-05],
        [-1.10793824e-03, -3.12016869e-04,  7.99481058e-05, ...,
         -1.89037458e-03, -7.06624612e-03,  3.45381140e-03],
        [-2.78524403e-03, -2.67025456e-03,  5.51061705e-04, ...,
         -3.06212809e-03, -1.01052644e-02,  3.84708750e-03],
        ...,
        [ 4.54738643e-03, -2.66303844e-03, -2.29560840e-03, ...,
          9.79077071e-04, -8.70374613e-04,  6.12644944e-04],
        [ 7.07244128e-03,  4.95957024e-03,  7.28933234e-03, ...,
         -8.61400040e-04,  4.97060502e-03,  4.66103759e-03],
        [ 8.98629020e-04,  2.95906328e-04,  3.46563593e-03, ...,
         -3.35454126e-03, -2.13499833e-03,  4.13955795e-03]],

       [[ 3.29102250e-03,  1.29417307e-03,  6.33061770e-03, ...,
         -4.37623064e-04, -6.69297122e-04,  6.34765485e-03],
        [ 4.79769520e-03, -4.91504092e-03,  5.

In [62]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [63]:
sampled_indices

<tf.Tensor: shape=(200, 1), dtype=int64, numpy=
array([[ 37],
       [ 69],
       [ 14],
       [ 96],
       [ 70],
       [ 33],
       [ 24],
       [ 75],
       [ 22],
       [ 83],
       [ 40],
       [ 27],
       [ 90],
       [ 43],
       [ 72],
       [ 33],
       [ 86],
       [ 70],
       [ 50],
       [ 71],
       [ 61],
       [ 47],
       [ 48],
       [ 96],
       [ 61],
       [ 21],
       [ 34],
       [ 25],
       [ 74],
       [  4],
       [ 73],
       [ 38],
       [ 27],
       [  4],
       [  0],
       [ 16],
       [ 49],
       [ 10],
       [ 34],
       [  6],
       [ 51],
       [ 72],
       [ 22],
       [ 26],
       [ 67],
       [ 22],
       [  4],
       [ 88],
       [ 28],
       [ 60],
       [ 87],
       [ 44],
       [ 83],
       [ 74],
       [ 19],
       [ 92],
       [ 65],
       [ 62],
       [ 96],
       [ 81],
       [ 43],
       [  7],
       [ 30],
       [ 69],
       [ 62],
       [ 59],
       [  4],
       [ 22],


In [64]:
# Reformatting to not be a lists of lists
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [65]:
sampled_indices

array([ 37,  69,  14,  96,  70,  33,  24,  75,  22,  83,  40,  27,  90,
        43,  72,  33,  86,  70,  50,  71,  61,  47,  48,  96,  61,  21,
        34,  25,  74,   4,  73,  38,  27,   4,   0,  16,  49,  10,  34,
         6,  51,  72,  22,  26,  67,  22,   4,  88,  28,  60,  87,  44,
        83,  74,  19,  92,  65,  62,  96,  81,  43,   7,  30,  69,  62,
        59,   4,  22,  60,  85, 101,   1,  62,  44,  21,  22,  36,  80,
        26,  97,  66,  60,  47,  50,   0,  96,  48,  65,   6,  44,  61,
        14,  63,  23,  80,  12,   9,  44, 102,  43,  90,  43,   8,   0,
        77,  51,  46,  37,  28,  57, 102,  69,  64,  99,  31,  65,  17,
        61,  41,  20,   9,  46,  54,  42,  83,  56,  56,   3,   5,  37,
        40,  35,  48,  22,  59,  88,   4,  80,  82,  66,  33,  11,  73,
        60,  32,   9,  31,  83,  44,  75,  92,  54,  93,  29,  10,  38,
        96,  42,  37,  42,  77,  45,  79,  39,   1,   1,  56,  56,  72,
        63,  47,  26,  64,  37,  63,  11,  38,  23,  93,  13, 10

In [66]:
epochs = 30

In [67]:
model.fit(dataset,epochs=epochs)

Epoch 1/30
92/92 ━━━━━━━━━━━━━━━━━━━━ 512s 5s/step - loss: 3.4820
Epoch 2/30
92/92 ━━━━━━━━━━━━━━━━━━━━ 505s 5s/step - loss: 2.2666
Epoch 3/30
92/92 ━━━━━━━━━━━━━━━━━━━━ 506s 5s/step - loss: 1.9711
Epoch 4/30
92/92 ━━━━━━━━━━━━━━━━━━━━ 506s 5s/step - loss: 1.7488
Epoch 5/30
92/92 ━━━━━━━━━━━━━━━━━━━━ 515s 6s/step - loss: 1.5955
Epoch 6/30
92/92 ━━━━━━━━━━━━━━━━━━━━ 571s 6s/step - loss: 1.4920
Epoch 7/30
92/92 ━━━━━━━━━━━━━━━━━━━━ 445s 5s/step - loss: 1.4226
Epoch 8/30
92/92 ━━━━━━━━━━━━━━━━━━━━ 439s 5s/step - loss: 1.3693
Epoch 9/30
92/92 ━━━━━━━━━━━━━━━━━━━━ 420s 5s/step - loss: 1.3284
Epoch 10/30
92/92 ━━━━━━━━━━━━━━━━━━━━ 410s 4s/step - loss: 1.2962
Epoch 11/30
92/92 ━━━━━━━━━━━━━━━━━━━━ 417s 5s/step - loss: 1.2679
Epoch 12/30
92/92 ━━━━━━━━━━━━━━━━━━━━ 410s 4s/step - loss: 1.2447
Epoch 13/30
92/92 ━━━━━━━━━━━━━━━━━━━━ 436s 5s/step - loss: 1.2231
Epoch 14/30
92/92 ━━━━━━━━━━━━━━━━━━━━ 414s 4s/step - loss: 1.2039
Epoch 15/30
92/92 ━━━━━━━━━━━━━━━━━━━━ 416s 4s/step - loss: 1.1867
Epoc

In [70]:
model.save('EM.Forst.h5')


In [71]:
from tensorflow.keras.models import load_model

In [72]:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)

model.load_weights('EM.Forst.h5')

model.build(tf.TensorShape([1, None]))


In [73]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (1, None, 64)          │         6,592 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_3 (GRU)                     │ (1, None, 1026)        │     3,361,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (1, None, 103)         │       105,781 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,473,549 (13.25 MB)

 Trainable params: 3,473,549 (13.25 MB)

 Non-trainable params: 0 (0.00 B)

In [83]:
def generate_text(model, start_seed, gen_size=100, temp=1.0):
    '''
    model: Trained Model to Generate Text
    start_seed: Initial Seed text in string form
    gen_size: Number of characters to generate

    The basic idea behind this function is to take in some seed text, format it so
    that it is in the correct shape for our network, then loop the sequence as
    we keep adding our own predicted characters.
    '''

    # Number of characters to generate
    num_generate = gen_size

    # Vectorizing starting seed text
    input_eval = [char_to_ind[s] for s in start_seed]

    # Expand to match batch format shape
    input_eval = tf.expand_dims(input_eval, 0)

    # Empty list to hold resulting generated text
    text_generated = []

    # Temperature effects randomness in our resulting text
    temperature = temp

    # Here batch size == 1
    # Reset states for stateful RNN layers
    for layer in model.layers:
        if hasattr(layer, 'reset_states'):
            layer.reset_states()

    for i in range(num_generate):

        # Generate Predictions
        predictions = model(input_eval)

        # Remove the batch shape dimension
        predictions = tf.squeeze(predictions, 0)

        # Use a categorical distribution to select the next character
        predictions = predictions / temperature
        predicted_id = tf.random.categorical(predictions, num_samples=1)[-1, 0].numpy()

        # Pass the predicted character for the next input
        input_eval = tf.expand_dims([predicted_id], 0)

        # Transform back to character letter
        text_generated.append(ind_to_char[predicted_id])

    return start_seed + ''.join(text_generated)





In [84]:
print(generate_text(model,"When she was",gen_size=100))


When she was develop in a dream.

Miss Quested, you walked man. Margaret now?”

“Yes.”

Then, with fire of the r
